/**
 * backend | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommunityDTO } from './communityDTO';


export interface GetMyCommunityResponseDTO { 
    community: CommunityDTO;
    isCommunityManager: boolean;
}

