/**
 * backend | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InitiativeDTO { 
    id: string;
    communityId: string;
    createdBy: string | null;
    name: string;
    description: string;
    categoryId: string | null;
    presetId: string | null;
    isPublic: boolean;
    isParticipating: boolean;
    latitude: number;
    longitude: number;
    startsAt: string;
    estimatedEndsAt: string | null;
    endedAt: string | null;
    createdAt: string;
    ecoPointsPerParticipant: number;
    participantCount: number;
    likeCount: number;
    isLiked: boolean;
}
